// Les types des differentes actions
export const ACTIONS = {
    LOADING: {
        GET_RESTAURANT_PENDING: 'GET_RESTAURANT_PENDING',
        GET_RESTAURANT_SUCCESS: 'GET_RESTAURANT_SUCCESS',
        GET_RESTAURANT_ERROR: 'GET_RESTAURANT_ERROR'
    },
    CRUD: {
        GET_RESTAURANT_ADD: 'GET_RESTAURANT_ADD',
        GET_RESTAURANT_DELETE: 'GET_RESTAURANT_DELETE',
        GET_RESTAURANT_READ: 'GET_RESTAURANT_READ'
    },
    LIST: {
        GET_NOTE_ADD: 'GET_NOTE_ADD',
        GET_COMMENT_ADD: 'GET_COMMENT_ADD',
    }

};
